# Generated by Django 5.0 on 2024-01-22 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeRegisterModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empId', models.IntegerField()),
                ('name', models.CharField(max_length=15)),
                ('phno', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
