# Generated by Django 5.0 on 2024-01-06 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.IntegerField()),
                ('emp_name', models.CharField(max_length=15)),
                ('emp_phno', models.IntegerField()),
                ('emp_email', models.EmailField(max_length=254)),
                ('emp_address', models.CharField(max_length=30)),
                ('emp_salary', models.DecimalField(decimal_places=3, max_digits=6)),
            ],
        ),
    ]
