# Generated by Django 5.0 on 2023-12-29 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empId', models.IntegerField()),
                ('empName', models.CharField(max_length=15)),
                ('empAddress', models.CharField(max_length=30)),
                ('empPhno', models.IntegerField()),
            ],
        ),
    ]
