# Generated by Django 5.0 on 2023-12-31 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModelWebApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regNo', models.IntegerField()),
                ('name', models.CharField(max_length=15)),
                ('phno', models.IntegerField()),
                ('address', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('courseName', models.CharField(max_length=10)),
                ('totalFee', models.IntegerField()),
            ],
        ),
    ]
